version: '3.5'
services:
  fuseki:
    # user: fuseki
    build:
      context: ./src/jena/fuseki-docker
      dockerfile: Dockerfile
    container_name: fuseki
    restart: always
    volumes:
      - rdf_data:/fuseki
      - staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./src/middleware
      dockerfile: Dockerfile
    container_name: middleware
    restart: always
    depends_on:
      - "fuseki"
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: npm run start --prefix ./boilerplates/runner

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - "middleware"
    environment:
      - PORT=5000
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"

volumes:
  rdf_data:
  staging:
networks:
  semapps:
    name: semapps_network
