name: Prettier formatting

on:
  pull_request:
    paths:
      - '**.css'
      - '**.js'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12.19.1'

      - name: Install prettier |
        run: |
          yarn install --prefix ./src/frontend
          yarn install --prefix ./src/middleware

      - name: Run prettier on frontend
        run: yarn run prettier --prefix ./src/frontend

      - name: Run prettier on middleware
        run: yarn run prettier --prefix ./src/middleware

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic prettier
          branch: ${{ github.head_ref }}
          push_options: --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
